// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class gpg_constants
{
        public const string leaderboard_4x4_1_minute = "CgkIkraRyo8PEAIQCg"; // <GPGSID>
        public const string achievement_welcome = "CgkIkraRyo8PEAIQAw"; // <GPGSID>
        public const string leaderboard_4x4_2_minutes = "CgkIkraRyo8PEAIQCw"; // <GPGSID>
        public const string achievement_3x3 = "CgkIkraRyo8PEAIQBw"; // <GPGSID>
        public const string leaderboard_4x4_3_minutes = "CgkIkraRyo8PEAIQDA"; // <GPGSID>
        public const string leaderboard_3x3_2_minutes = "CgkIkraRyo8PEAIQCQ"; // <GPGSID>
        public const string achievement_4x4 = "CgkIkraRyo8PEAIQBg"; // <GPGSID>
        public const string leaderboard_3x3_30_seconds = "CgkIkraRyo8PEAIQAQ"; // <GPGSID>
        public const string leaderboard_3x3_1_minute = "CgkIkraRyo8PEAIQCA"; // <GPGSID>
        public const string achievement_ = "CgkIkraRyo8PEAIQBQ"; // <GPGSID>
        public const string achievement_congratz = "CgkIkraRyo8PEAIQBA"; // <GPGSID>

}

